// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Account struct {
	ID        int32        `json:"id"`
	Owner     string       `json:"owner"`
	Balance   int32        `json:"balance"`
	Currency  string       `json:"currency"`
	Createdat sql.NullTime `json:"createdat"`
}

type Entry struct {
	ID        int32        `json:"id"`
	AccountID int32        `json:"account_id"`
	Amount    int32        `json:"amount"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Transfer struct {
	ID            int32        `json:"id"`
	FromAccountID int32        `json:"from_account_id"`
	ToAccountID   int32        `json:"to_account_id"`
	Amount        int32        `json:"amount"`
	CreatedAt     sql.NullTime `json:"created_at"`
}
