// the Queries struct generated by the sqlc does not support
// the transaction as transaction is the small unit of work
// often made up of multiple db operations but the
// queries struct generated exeucutes one operation on one specific
//table

//  till now while writing the unit tests of the
// accounts and entries one function is not related
// with other if related we call it again manually while writing the
// test,the query struct executes single operation on single table at a
// time but in money transfer we need several db operations to be executed say
// first create a transfer record , then create a entry for account one then for
// second and then subtract the amount from account 1 and add in account 2 and
// we cannot reflect in the table and write in the disk until all operations is
// executed because performing then individually will not provide atomicity and
// chaos will happen in case of system failure that's why need to extend its functionality
// by embedding is into another struct store called composition

package db

import (
	"context"
	"database/sql"
	"fmt"
)

// this is  the preffered way of inheriting the property
// in the golang instead of inheritance

// we are using sql.DB instead of sql.Tx becaue store
// is going to be in the memory by the start of the server till end
// and sql.DB is will be in memory for permanent where as
//sql.Tx lifespan is few milliseconds, it will immedietly closed
// after one transaction
type Store struct{
	*Queries
	db *sql.DB 
}

// New store creates new store 
func NewStore(db *sql.DB) *Store{
	return &Store{
		db: db,
		Queries: New(db),//New functions takes the db object and returns queries 
	}
} 
 

//execTx executes a function within a database transaction
func (store *Store) execTx(ctx context.Context, fn func(*Queries)error) error{
	// This function core motive is to check if there is any 
	// error in executing any query then rollback do not write 
	// anything (rollback) otherwise commit (write in db)

	tx, err := store.db.BeginTx(ctx, nil) 
	// this tells the db that we are going to execute some unit 
	// of db operations(Transaction) do not write anything in table 
	// until all op. are done

	if err != nil{
		return err
	}

	//passing the query to check is there any error in query

	q:= New(tx)
	err = fn(q)

	if err != nil {
		// rollback and check is there any error in rollback
		rbErr := tx.Rollback()
		if rbErr != nil{
			return fmt.Errorf("txErr %v rbErr %v", err, rbErr)
		}
		return err
	}

	// if reached here then there is no error i.e. commit the changes
	return tx.Commit()

}

type TransferTxParams struct{
	FromAccountId int64 `json:"from_account_id"`
	ToAccountId int64 `json:"to_account_id"`
	Amount       int64 `json:"amount"`
}

// TransferTxResult is the result of the transfer transaction
type TransferTxResult struct{
	Transfer Transfer `json:"transfer"`
	FromAccount Account `json:"from_account"`
	ToAccount Account `json:"to_account"`
	FromEntry Entry `json:"from_entry"` //entry of the account which records money is moving out
	ToEntry Entry `json:"to_entry"` //entry of the account which records money is moving in
}

//This TransferTx function perform amount transfer from acc1 to acc2 includes transfer record,
// account entry for both accounts , amount adjustments in both account in a transaction
func (store *Store) TransferTx(ctx context.Context, arg TransferTxParams ) (TransferTxResult, error){
	var result TransferTxResult

	err := store.execTx(ctx, func(q *Queries) error {
		//create the transfer
		transferCreateResult , err := q.CreateTransfer(ctx, CreateTransferParams{
			FromAccountID: int32(arg.FromAccountId),
			ToAccountID: int32(arg.ToAccountId),
			Amount: int32(arg.Amount),
		})
		if err != nil{
			return fmt.Errorf("Error %v in creating transfer", err)
		}		
		transferId, err := transferCreateResult.LastInsertId()
		if err != nil{
			return err
		}
		
		result.Transfer, err = q.GetTransfer(ctx, int32(transferId))
		
		fromEntryResult , err := q.CreateEntry(ctx, CreateEntryParams{
			AccountID: int32(arg.FromAccountId),
			Amount: int32(-arg.Amount),
		})

		if err != nil {
			return err
		}

		fromEntryId , err := fromEntryResult.LastInsertId()
		if err != nil{
			return err
		}

		result.FromEntry , err = q.GetEntry(ctx, int32(fromEntryId))

		toEntryResult, err := q.CreateEntry(ctx, CreateEntryParams{
			AccountID: int32(arg.ToAccountId),
			Amount: int32(+arg.Amount),
		})

		if(err != nil){
			return err
		}

		toEntryId, err := toEntryResult.LastInsertId()

		if err != nil{
			return err
		}

		result.ToEntry, err = q.GetEntry(ctx, int32(toEntryId))

		// TODO: update account balance


		
		return nil
	})
	return result, err
}


