// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package db

import (
	"context"
	"database/sql"
)

const getTransfer = `-- name: GetTransfer :execresult
SELECT id, from_account_id, to_account_id, amount, created_at FROM transfers 
WHERE id = ? LIMIT 1
`

func (q *Queries) GetTransfer(ctx context.Context, id int32) (sql.Result, error) {
	return q.db.ExecContext(ctx, getTransfer, id)
}

const transferAmount = `-- name: TransferAmount :execresult
INSERT INTO transfers(
    from_account_id,
    to_account_id,
    amount
)VALUES(?,?,?)
`

type TransferAmountParams struct {
	FromAccountID int32 `json:"from_account_id"`
	ToAccountID   int32 `json:"to_account_id"`
	Amount        int32 `json:"amount"`
}

func (q *Queries) TransferAmount(ctx context.Context, arg TransferAmountParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, transferAmount, arg.FromAccountID, arg.ToAccountID, arg.Amount)
}

const transferLists = `-- name: TransferLists :execresult
SELECT id, from_account_id, to_account_id, amount, created_at FROM transfers
WHERE from_account_id = ? OR 
to_account_id = ?
ORDER BY id
LIMIT  ?
OFFSET  ?
`

type TransferListsParams struct {
	FromAccountID int32 `json:"from_account_id"`
	ToAccountID   int32 `json:"to_account_id"`
	Limit         int32 `json:"limit"`
	Offset        int32 `json:"offset"`
}

func (q *Queries) TransferLists(ctx context.Context, arg TransferListsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, transferLists,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Limit,
		arg.Offset,
	)
}
